# --- Docker Containers Surveillance (stdout) ---
# Block 1: Traefik
source: docker
container_name:
 - stack-traefik-1
labels:
  type: traefik

---

# --- SFTP Container Surveillance (stdout) ---
# Block 2: SFTP (Sidecar)
source: docker
container_name:
 - stack-sftp-access-1
labels:
  type: syslog

## NOTE: THE SEPARATOR --- IS REQUIRED BETWEEN THE TWO BLOCKS
